source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'Parser' do
    target 'VBMathParserExamples' do
        pod 'VBException', '~> 1.0'
    end

    target 'VBMathParserExamplesTests' do
        inherit! :search_paths
        
        pod 'Expecta', '~> 1.0'
        pod 'OCMock', '~> 3.2'
    end

end