source 'https://github.com/CocoaPods/Specs.git'

target 'VBMathParserExamples' do

    pod 'VBException', '~> 1.0'

    target 'VBMathParserExamplesTests' do
        pod 'Expecta', '~> 1.0'
        pod 'OCMock', '~> 3.2'
    end

end
